# Generated by Django 5.2 on 2025-04-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='paymob_order_id',
            field=models.CharField(blank=True, db_index=True, help_text="Paymob's order ID for the payment attempt", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paymob_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text="Paymob's unique transaction ID", max_length=100, null=True, unique=True),
        ),
    ]
