# Generated by Django 5.2 on 2025-05-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_carreview_merchantreview_servicereview_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceReview',
        ),
    ]
