# Generated by Django 5.2 on 2025-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_category_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='car_makes/icons/'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='car_models/icons/'),
        ),
    ]
