# Generated by Django 5.2.6 on 2025-09-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmake_icon_carmodel_icon'),
        ('merchants', '0012_pageadvert_pageadvertimage_pageadvertvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='merchants.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
