# Generated by Django 5.2 on 2025-05-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
