# Generated by Django 5.2 on 2025-05-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_is_featured'),
        ('merchants', '0006_merchant_tiktok_url_merchant_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='merchants.service'),
        ),
    ]
