# Generated by Django 5.2 on 2025-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_service'),
        ('merchants', '0009_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='service',
        ),
        migrations.AddField(
            model_name='deal',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='deals', to='merchants.service'),
        ),
    ]
