# Generated by Django 5.2 on 2025-05-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_remove_deal_service_deal_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='services',
        ),
    ]
