# Generated by Django 5.2 on 2025-04-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True)),
                ('redemption_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('refunded', 'Refunded')], db_index=True, default='issued', max_length=10)),
            ],
            options={
                'ordering': ['-purchase_datetime'],
            },
        ),
    ]
