# Generated by Django 5.2 on 2025-04-29 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='deals.deal'),
        ),
    ]
