# Generated by Django 5.2 on 2025-05-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
    ]
