# Generated by Django 5.2 on 2025-05-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmake_icon_carmodel_icon'),
        ('users', '0007_remove_vehicle_license_plate_remove_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carmake'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carmodel'),
        ),
    ]
