# Generated by Django 5.2 on 2025-04-29 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchant_logos/')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve merchants before they can post deals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address_text', models.TextField(blank=True, help_text='Full address text for display')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Downtown Branch, Nasr City Branch', max_length=100)),
                ('address_text', models.TextField(blank=True, help_text='Full address text for display')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='merchants.merchant')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['merchant__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MerchantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('staff', 'Staff'), ('accountant', 'Accountant')], max_length=20)),
                ('branch', models.ForeignKey(blank=True, help_text='Assign to specific branch if role is branch-specific (e.g., Branch Manager, Staff)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='merchants.branch')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='merchants.merchant')),
            ],
            options={
                'ordering': ['merchant__name', 'user__username'],
            },
        ),
    ]
