# Generated by Django 5.2 on 2025-04-29 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL

class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, disable foreign key checks
        RunSQL(
            "SET FOREIGN_KEY_CHECKS=0;",
            reverse_sql="SET FOREIGN_KEY_CHECKS=1;"
        ),
        # Then drop the existing table if it exists
        RunSQL(
            "DROP TABLE IF EXISTS merchants_category;",
            reverse_sql=""
        ),
        # Re-enable foreign key checks
        RunSQL(
            "SET FOREIGN_KEY_CHECKS=1;",
            reverse_sql="SET FOREIGN_KEY_CHECKS=0;"
        ),
        # Check and remove contact_email if it exists
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'contact_email';
            
            SET @query = IF(@exists > 0, 
                'ALTER TABLE merchants_merchant DROP COLUMN contact_email',
                'SELECT "Column contact_email does not exist"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and remove is_approved if it exists
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'is_approved';
            
            SET @query = IF(@exists > 0, 
                'ALTER TABLE merchants_merchant DROP COLUMN is_approved',
                'SELECT "Column is_approved does not exist"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add latitude to branch if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_branch' 
            AND column_name = 'latitude';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_branch ADD COLUMN latitude decimal(9,6) NULL',
                'SELECT "Column latitude already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add longitude to branch if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_branch' 
            AND column_name = 'longitude';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_branch ADD COLUMN longitude decimal(9,6) NULL',
                'SELECT "Column longitude already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add latitude to merchant if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'latitude';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchant ADD COLUMN latitude decimal(9,6) NULL',
                'SELECT "Column latitude already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add longitude to merchant if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'longitude';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchant ADD COLUMN longitude decimal(9,6) NULL',
                'SELECT "Column longitude already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add created_at to branch if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_branch' 
            AND column_name = 'created_at';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_branch ADD COLUMN created_at datetime(6) NULL',
                'SELECT "Column created_at already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add updated_at to branch if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_branch' 
            AND column_name = 'updated_at';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_branch ADD COLUMN updated_at datetime(6) NULL',
                'SELECT "Column updated_at already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add created_at to merchant if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'created_at';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchant ADD COLUMN created_at datetime(6) NULL',
                'SELECT "Column created_at already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add updated_at to merchant if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'updated_at';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchant ADD COLUMN updated_at datetime(6) NULL',
                'SELECT "Column updated_at already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add created_at to merchantuser if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchantuser' 
            AND column_name = 'created_at';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchantuser ADD COLUMN created_at datetime(6) NULL',
                'SELECT "Column created_at already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add updated_at to merchantuser if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchantuser' 
            AND column_name = 'updated_at';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchantuser ADD COLUMN updated_at datetime(6) NULL',
                'SELECT "Column updated_at already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add email to branch if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_branch' 
            AND column_name = 'email';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_branch ADD COLUMN email varchar(254) NULL',
                'SELECT "Column email already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add email to merchant if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'email';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchant ADD COLUMN email varchar(254) NULL',
                'SELECT "Column email already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add is_main to branch if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_branch' 
            AND column_name = 'is_main';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_branch ADD COLUMN is_main bool NOT NULL DEFAULT 0',
                'SELECT "Column is_main already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add is_featured to merchant if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'is_featured';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchant ADD COLUMN is_featured bool NOT NULL DEFAULT 0',
                'SELECT "Column is_featured already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add is_verified to merchant if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchant' 
            AND column_name = 'is_verified';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchant ADD COLUMN is_verified bool NOT NULL DEFAULT 0',
                'SELECT "Column is_verified already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Check and add is_active to merchantuser if it doesn't exist
        RunSQL(
            """
            SELECT COUNT(*) INTO @exists 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = 'merchants_merchantuser' 
            AND column_name = 'is_active';
            
            SET @query = IF(@exists = 0, 
                'ALTER TABLE merchants_merchantuser ADD COLUMN is_active bool NOT NULL DEFAULT 1',
                'SELECT "Column is_active already exists"');
            
            PREPARE stmt FROM @query;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=""
        ),
        # Then create the Category model
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True, blank=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        # Rest of your migration operations...
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['merchant__name', 'name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='merchantuser',
            options={'ordering': ['merchant__name', 'user__username']},
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_covers/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address_text',
            field=models.TextField(blank=True, help_text='Full address text for display'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='e.g., Downtown Branch, Nasr City Branch', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='address_text',
            field=models.TextField(blank=True, help_text='Full address text for display'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('staff', 'Staff'), ('accountant', 'Accountant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MerchantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='merchant_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField(help_text='Estimated duration of the service')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='merchants.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='merchants.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='merchantuser',
            name='branch',
        ),
    ] 