# Generated by Django 5.2 on 2025-04-29 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True, blank=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        # Rest of your migration operations...
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['merchant__name', 'name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='merchantuser',
            options={'ordering': ['merchant__name', 'user__username']},
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_covers/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address_text',
            field=models.TextField(blank=True, help_text='Full address text for display'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='e.g., Downtown Branch, Nasr City Branch', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='address_text',
            field=models.TextField(blank=True, help_text='Full address text for display'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('staff', 'Staff'), ('accountant', 'Accountant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MerchantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='merchant_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField(help_text='Estimated duration of the service')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='merchants.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='merchants.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='merchantuser',
            name='branch',
        ),
    ] 