# Generated by Django 5.2 on 2025-05-13 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_category_alter_branch_options_alter_merchant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-is_main', 'name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['-is_featured', '-rating', 'name']},
        ),
        migrations.AlterModelOptions(
            name='merchantimage',
            options={'ordering': ['-is_primary', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='merchantuser',
            options={'ordering': ['merchant', 'role']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['merchant__name', 'name']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.AlterUniqueTogether(
            name='merchantuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='service',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='merchants.category'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='merchantuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='merchantuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='address_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='merchants/covers/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='merchants/logos/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='merchantimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='merchantimage',
            name='image',
            field=models.ImageField(upload_to='merchants/gallery/'),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='merchantuser',
            unique_together={('merchant', 'user')},
        ),
    ]
