# Generated by Django 5.2 on 2025-05-13 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_branch_options_alter_merchant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='merchants.category', verbose_name='Parent'),
        ),
    ]
