# Generated by Django 5.2 on 2025-05-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_merchant_tiktok_url_merchant_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='merchants.branch'),
        ),
    ]
