# Generated by Django 5.2 on 2025-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_and_more'),
        ('deals', '0006_remove_deal_services'),
        ('merchants', '0009_alter_service_category'),
        ('reviews', '0004_delete_servicereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantimage',
            options={'ordering': ['image_type', 'order', '-is_primary', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='merchantimage',
            name='image_type',
            field=models.CharField(choices=[('cover', 'Cover Image'), ('gallery', 'Gallery Image'), ('logo', 'Logo')], default='gallery', max_length=10),
        ),
        migrations.AddField(
            model_name='merchantimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='merchantimage',
            name='image',
            field=models.ImageField(upload_to='merchants/images/'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantimage',
            unique_together={('merchant', 'image_type', 'is_primary')},
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
