# Generated by Django 5.2.6 on 2025-09-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0011_merchant_makes_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('category', 'Category'), ('merchant', 'Merchant')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageAdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adverts/images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PageAdvertVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='adverts/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['display_order', '-is_featured', '-rating', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='merchantimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='display_order',
            field=models.PositiveIntegerField(default=1000, help_text='Lower numbers appear first on the merchants page.'),
        ),
        migrations.AddConstraint(
            model_name='merchantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('merchant', 'image_type'), name='unique_primary_image_per_type_per_merchant'),
        ),
        migrations.AddField(
            model_name='pageadvert',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.category'),
        ),
        migrations.AddField(
            model_name='pageadvert',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='pageadvertimage',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='merchants.pageadvert'),
        ),
        migrations.AddField(
            model_name='pageadvertvideo',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='merchants.pageadvert'),
        ),
    ]
