# Generated by Django 5.2 on 2025-05-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('merchants', '0009_alter_service_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'merchant')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='service',
        ),
    ]
