# Generated by Django 5.2 on 2025-05-26 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_and_more'),
        ('deals', '0006_remove_deal_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.deal'),
        ),
    ]
